# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 4.0.0+1.21.1
maven_group = dev.sleepy_evelyn.packwizml
archives_name = packwizml
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.1
yarn_mappings = 1.21.1+build.1

# Dependencies
fabric_loader_version = 0.18.3
neoforge_version = 21.1.215
yarn_mappings_patch_neoforge_version = 1.21+build.6
toml4j_version = 0.7.2
